### ISSUE TITLE
Unable to Install using yarn

### ISSUE THREAD

**Issue by TejashreeG** [knightjdr/angular-drag-resize#1]
I am trying to install package using yarn add angular-drag-resize.

I am getting below error: 
error An unexpected error occurred: "http://registry.npmjs.org/angular-drag-resize: Not found".

Is this module not accessible using yarn?

Thanks

**Comment by knightjdr** [comment]
It wasn't published to npm but I've done that now. Try again and see if it works.

**Comment by TejashreeG** [comment]
Hi I am able to add the module now through yarn. Thanks :+1:
