### ISSUE TITLE
Plunker Not Found

### ISSUE THREAD

**Issue by ruisilva450** [knightjdr/angular-drag-resize#2]
Your plunker link leads to a "Not Found" page

https://github.com/knightjdr/angular-drag-resize/commit/eaf6fbe887ac855ee07e69138d223a3a721fffe6#diff-04c6e90faac2675aa89e2176d2eec7d8R6

**Comment by knightjdr** [comment]
It looks like in some cases Plunker is redirecting to their alpha site which doesn't have my plunk. It does this to me on mobile (Chrome) but not on desktop with Chrome, Firefox or Safari.

Just make sure the url reads: https://plnkr.co/I8ebvx and not https://next.plnkr.co/I8ebvx
